support running test on mac for flutter branch workflow
QuickBirdEng/workflows pull request #11
Opened 2023-12-19 09:08 UTC by eldrigo

2023-12-19 09:11 UTC, TechPiranja approved these changes

2023-12-19 09:16 UTC, acpoppe requested changes

2023-12-19 09:16 UTC, acpoppe commented on .github/workflows/flutter-branch.yml
> +        description: "shoudl use mac runners to run test"
NIT: typo here

2023-12-19 09:16 UTC, acpoppe commented on .github/workflows/flutter-branch.yml
> +      ["${{ inputs.use-mac-runners-for-test && 'macOS' || 'self-hosted'  }}"]
Self-hosted needs to be there either way.

` ["self-hosted"${{ inputs.use-mac-runners-for-test && ', "macOS" || ' ' }}]`

2023-12-19 09:16 UTC, acpoppe commented on .github/workflows/flutter-branch.yml
> +      ["${{ inputs.use-mac-runners-for-test && 'macOS' || 'self-hosted'  }}"]
See above

2023-12-19 09:17 UTC, acpoppe commented on .github/workflows/flutter-branch.yml
> +      ["${{ inputs.use-mac-runners-for-test && 'macOS' || 'self-hosted'  }}"]
You could also do

`[${{ inputs.use-mac-runners-for-test && ' "self-hosted", "macOS" ' || ' "self-hosted" ' }}]`

2024-03-07 21:11 UTC, eldrigo commented
redundent.

2024-03-07 21:11 UTC, closed without merging